# Supabase CLI Configuration
project_id = "fckqzdphfqufywywxohh"

[db]
# PostgreSQL database connection settings
host = "localhost"
port = 5432
user = "postgres"
password = "root"
database = "postgres"
schema = "public"

[db.pooler]
enabled = false
port = 6543
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[storage]
enabled = true
file_size_limit = "50MiB"

[functions]
verify_jwt = false
